djangoBasics/BraniacLMC/authap/urls.py
from authap.apps import AuthapConfig
from django.urls import path
from authap.views import CustomLoginView, RegisterView, CustomLogoutView, EditView

app_name = AuthapConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('edit/', EditView.as_view(), name='edit'),
]

djangoBasics/BraniacLMC/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainap import views
from mainap.apps import MainapConfig
from django.views.generic import RedirectView

app_name = MainapConfig.name

urlpatterns = [
    path('', RedirectView.as_view(url='mainap/')),
    path('mainap/', include('mainap.urls', namespace='mainap')),
    path('admin/', admin.site.urls),
    path('authap/', include('authap.urls', namespace='authap')),
    path('social_auth/', include('social_django.urls', namespace='social'))
]

# добавляется для работы джанго с медиа
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoBasics/BraniacLMC/mainap/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from mainap import views
from mainap.apps import MainapConfig
from django.views.generic import RedirectView

app_name = MainapConfig.name

urlpatterns = [
    path('', RedirectView.as_view(url='index.html')),
    path('index.html', views.MainPageView.as_view(), name='main_page'),
    path('news/', views.NewsPageView.as_view(), name='news'),
    path('news/<int:page>', views.NewsPageViewWithPaginator.as_view(), name='news_paginator'),
    path('courses/', views.CoursesPageView.as_view(), name='courses'),
    path('contacts/', views.ContactsPageView.as_view(), name='contacts'),
    path('doc_site/', views.DocSitePageView.as_view(), name='doc_site'),
    path('login/', views.LoginPageView.as_view(), name='login'),
]

djangoBasics/BraniacLMC/mainap/models.py
from django.db import models


NULLALLABLE = {'blank': True, 'null': True}
# body = models.TextField(blank=True, null=True, verbose_name="Body")


class BaseModel(models.Model):
    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        abstract = True


class News(BaseModel):
    title = models.CharField(max_length=256, verbose_name="Title")
    preamble = models.CharField(max_length=1024, verbose_name="Preamble")
    body = models.TextField(**NULLALLABLE, verbose_name="Body")
    body_as_markdown = models.BooleanField(default=False, verbose_name="As markdown")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.title}"

    class Meta:
        ordering = ("created", "title")


class Courses(BaseModel):
    name = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Cost", default=0)
    cover = models.CharField(max_length=25, default="no_image.svg", verbose_name="Cover")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited")

    def __str__(self) -> str:
        return f"{self.pk} {self.name}"

    class Meta:
        ordering = ("name", "created")


class Lesson(BaseModel):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Lesson number")
    title = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", **NULLALLABLE)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.course.name} | {self.num} | {self.title}"

    class Meta:
        ordering = ("course", "num")


class CourseTeachers(BaseModel):
    course = models.ManyToManyField(Courses)
    name_first = models.CharField(max_length=128, verbose_name="Name")
    name_second = models.CharField(max_length=128, verbose_name="Surname")
    day_birth = models.DateField(verbose_name="Birth date")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk}, {self.name_second}, {self.name_first}"

    class Meta:
        ordering = ("name_second", "name_first")

djangoBasics/BraniacLMC/mainap/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View
from django.views.generic import TemplateView
from django.urls import resolve
from datetime import datetime, timedelta
import json


# def check_kwargs(request, **kwargs):
#     return HttpResponse(f'kwargs:<br>{kwargs}')
#
#
# class HeloWorldView(View):
#     def get(self, *args):
#         return HttpResponse('Hello World!')


class MainPageView(TemplateView):
    template_name = 'mainap/index.html'


class NewsPageView(TemplateView):
    template_name = 'mainap/news.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        with open('mainap/templates/mainap/news.json') as file:
            stock = json.load(file)
        context['json_news'] = stock
        context['object_list'] = [
            {
                'news_title': 'Первый новостной заголовок',
                'news_text': 'Первый новостной текст',
                'news_number': 1,
                'news_date': datetime.now()
            }, {
                'news_title': 'Второй новостной заголовок',
                'news_text': 'Второй новостной текст',
                'news_number': 2,
                'news_date': datetime.now() - timedelta(1)
            }, {
                'news_title': 'Третий новостной заголовок',
                'news_text': 'Третий новостной текст',
                'news_number': 3,
                'news_date': datetime.now() - timedelta(2)
            }, {
                'news_title': 'Четвертый новостной заголовок',
                'news_text': 'Четвертый новостной текст',
                'news_number': 4,
                'news_date': datetime.now() - timedelta(3)
            }, {
                'news_title': 'Пятый новостной заголовок',
                'news_text': 'Пятый новостной текст',
                'news_number': 5,
                'news_date': datetime.now() - timedelta(4)
            }
        ]
        return context


class NewsPageViewWithPaginator(NewsPageView):

    def get_context_data(self, page, **kwargs):
        context = super().get_context_data(page=page, **kwargs)
        context['page_num'] = page
        return context


class CoursesPageView(TemplateView):
    template_name = 'mainap/courses_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = [
            {
                'course_picture': 'img/course001.jpg',
                'course_name': 'Web Python',
                'course_number': 1
            }, {
                'course_picture': 'img/course002.jpg',
                'course_name': 'Web Golang',
                'course_number': 2
            }, {
                'course_picture': 'img/course003.jpg',
                'course_name': 'Web JavaScript',
                'course_number': 3
            }, {
                'course_picture': 'img/course004.jpg',
                'course_name': 'Web Java',
                'course_number': 4
            }, {
                'course_picture': 'img/course005.jpg',
                'course_name': 'Web PHP',
                'course_number': 5
            }, {
                'course_picture': 'img/course006.jpg',
                'course_name': 'Python AI',
                'course_number': 6
            }, {
                'course_picture': 'img/course007.jpg',
                'course_name': 'DevOps',
                'course_number': 7
            }
        ]
        return context


class ContactsPageView(TemplateView):
    template_name = 'mainap/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = [
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHcrhA',
                'city': 'Санкт‑Петербург',
                'phone': '+7-999-11-11111',
                'email': 'geeklab@spb.ru',
                'address': 'территория Петропавловская крепость, 3'
            },
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHX3xB',
                'city': 'Казань',
                'phone': '+7-999-22-22222',
                'email': 'geeklab@kz.ru',
                'address': 'территория Кремль, 11, Казань, Республика Татарстан, Россия'
            },
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHh9kD',
                'city': 'Москва',
                'phone': '+7-999-33-33333',
                'email': 'geeklab@msk.ru',
                'address': 'Красная площадь, 7, Москва, Россия'
            }
        ]
        return context


class DocSitePageView(TemplateView):
    template_name = 'mainap/doc_site.html'


class LoginPageView(TemplateView):
    template_name = 'mainap/login.html'

djangoBasics/BraniacLMC/mainap/templates/mainap/includes/footer.html
{% load static %}
   <!-- Footer -->

    <div class="container-lg mt-auto">
        <hr>
        <div class="row justify-content-center">
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Braniac</strong>
                </p>
                <p>
                <ul class="list-unstyled">
                    <li><a href=" {% url 'mainap:main_page' %}">Домашняя</a></li>
                    <li><a href="{% url 'mainap:news' %}">Новости</a></li>
                    <li><a href="{% url 'authap:login' %}">Войти</a></li>
                </ul>
                </p>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Полезное</strong>
                </p>
                <p>
                <ul class="list-unstyled">
                    <li><a href="#">Положения &amp; Условия</a></li>
                    <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
                    <li><a href="#">Документация по API</a></li>
                    <li><a href="{% url 'mainap:doc_site' %}">Документация по сайту</a></li>
                </ul>
                </p>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Мы в социальных сетях</strong>
                </p>
                <p>
                <div class="row justify-content-around">
                    <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
                </div>
                </p>
                <p>
                    <strong>Наше приложение</strong>
                </p>
                <p>
                <div class="row justify-content-around">
                    <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-windows fa-2x"></i></a></div>
                </div>
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div>
                <p><small>&copy; GeekBrains 2022</small></p>
            </div>
        </div>
    </div>

    <!-- /Footer -->


    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- ChartJs -->
    <script src="{% static 'js/Chart.min.js' %}"></script>

    <!-- FontAwesome -->
    <script src="{% static 'js/fontawesome.all.min.js' %}"></script>

djangoBasics/BraniacLMC/mainap/templates/mainap/includes/main_menu.html
{% load static %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'mainap:main_page' %}">
                <img src="{% static 'img/logo.png' %}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% if request.resolver_match.view_name == 'mainap:news' %} active{% endif %}">
                        <a class="nav-link" href=" {% url 'mainap:news' %}">Новости</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.view_name == 'mainap:courses' %} active{% endif %}">
                        <a class="nav-link" href=" {% url 'mainap:courses' %}">Курсы</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Профиль
                        </a>
                        <div class="dropdown-menu" aria-labelledby="ddProfile">
                            <a class="dropdown-item" href="#">Редактировать профиль</a>
                            <a class="dropdown-item" href="#">Мои курсы</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Модерация</a>
                            <a class="dropdown-item" href="#">Административный раздел</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Выход</a>
                        </div>
                    </li>
                    <li class="nav-item {% if request.resolver_match.view_name == 'mainap:contacts' %} active{% endif %}">
                        <a class="nav-link" href="{% url 'mainap:contacts' %}">Контакты</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                         <a class="nav-link" href="{% url 'authap:edit' %}">{{ user.username|default:'Вы не авторизованы' }}</a>
                        </li>
                        <li>
                         <a class="nav-link" href="{% url 'authap:logout' %}">Выход</a>
                        </li>
                    {% else %}
                        <li>
                         <a class="nav-link" href="{% url 'authap:login' %}">Вход</a>
                        </li>
                    {% endif %}
                </ul>
                <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a href="#">🇬🇧</a></span>
            </div>
        </div>
    </nav>