djangoBasics/BraniacLMC/authap/urls.py
from authap.apps import AuthapConfig
from django.urls import path
from authap.views import CustomLoginView, RegisterView, CustomLogoutView, EditView

app_name = AuthapConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('edit/', EditView.as_view(), name='edit'),
]

djangoBasics/BraniacLMC/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainap import views
from mainap.apps import MainapConfig
from django.views.generic import RedirectView

app_name = MainapConfig.name

urlpatterns = [
    path('', RedirectView.as_view(url='mainap/')),
    path('mainap/', include('mainap.urls', namespace='mainap')),
    path('admin/', admin.site.urls),
    path('authap/', include('authap.urls', namespace='authap')),
    path('social_auth/', include('social_django.urls', namespace='social'))
]

# добавляется для работы джанго с медиа
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoBasics/BraniacLMC/mainap/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from mainap import views
from mainap.apps import MainapConfig
from django.views.generic import RedirectView

app_name = MainapConfig.name

urlpatterns = [
    path('', RedirectView.as_view(url='index.html')),
    path('index.html', views.MainPageView.as_view(), name='main_page'),
    path('news/', views.NewsPageView.as_view(), name='news'),
    path('news/<int:page>', views.NewsPageViewWithPaginator.as_view(), name='news_paginator'),
    path('courses/', views.CoursesPageView.as_view(), name='courses'),
    path('contacts/', views.ContactsPageView.as_view(), name='contacts'),
    path('doc_site/', views.DocSitePageView.as_view(), name='doc_site'),
    path('login/', views.LoginPageView.as_view(), name='login'),
]

djangoBasics/BraniacLMC/mainap/models.py
from django.db import models


NULLALLABLE = {'blank': True, 'null': True}
# body = models.TextField(blank=True, null=True, verbose_name="Body")


class BaseModel(models.Model):
    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        abstract = True


class News(BaseModel):
    title = models.CharField(max_length=256, verbose_name="Title")
    preamble = models.CharField(max_length=1024, verbose_name="Preamble")
    body = models.TextField(**NULLALLABLE, verbose_name="Body")
    body_as_markdown = models.BooleanField(default=False, verbose_name="As markdown")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.title}"

    class Meta:
        ordering = ("created", "title")


class Courses(BaseModel):
    name = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Cost", default=0)
    cover = models.CharField(max_length=25, default="no_image.svg", verbose_name="Cover")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited")

    def __str__(self) -> str:
        return f"{self.pk} {self.name}"

    class Meta:
        ordering = ("name", "created")


class Lesson(BaseModel):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Lesson number")
    title = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", **NULLALLABLE)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.course.name} | {self.num} | {self.title}"

    class Meta:
        ordering = ("course", "num")


class CourseTeachers(BaseModel):
    course = models.ManyToManyField(Courses)
    name_first = models.CharField(max_length=128, verbose_name="Name")
    name_second = models.CharField(max_length=128, verbose_name="Surname")
    day_birth = models.DateField(verbose_name="Birth date")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk}, {self.name_second}, {self.name_first}"

    class Meta:
        ordering = ("name_second", "name_first")

djangoBasics/BraniacLMC/mainap/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View
from django.views.generic import TemplateView
from django.urls import resolve
from datetime import datetime, timedelta
import json


# def check_kwargs(request, **kwargs):
#     return HttpResponse(f'kwargs:<br>{kwargs}')
#
#
# class HeloWorldView(View):
#     def get(self, *args):
#         return HttpResponse('Hello World!')


class MainPageView(TemplateView):
    template_name = 'mainap/index.html'


class NewsPageView(TemplateView):
    template_name = 'mainap/news.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        with open('mainap/templates/mainap/news.json') as file:
            stock = json.load(file)
        context['json_news'] = stock
        context['object_list'] = [
            {
                'news_title': 'Первый новостной заголовок',
                'news_text': 'Первый новостной текст',
                'news_number': 1,
                'news_date': datetime.now()
            }, {
                'news_title': 'Второй новостной заголовок',
                'news_text': 'Второй новостной текст',
                'news_number': 2,
                'news_date': datetime.now() - timedelta(1)
            }, {
                'news_title': 'Третий новостной заголовок',
                'news_text': 'Третий новостной текст',
                'news_number': 3,
                'news_date': datetime.now() - timedelta(2)
            }, {
                'news_title': 'Четвертый новостной заголовок',
                'news_text': 'Четвертый новостной текст',
                'news_number': 4,
                'news_date': datetime.now() - timedelta(3)
            }, {
                'news_title': 'Пятый новостной заголовок',
                'news_text': 'Пятый новостной текст',
                'news_number': 5,
                'news_date': datetime.now() - timedelta(4)
            }
        ]
        return context


class NewsPageViewWithPaginator(NewsPageView):

    def get_context_data(self, page, **kwargs):
        context = super().get_context_data(page=page, **kwargs)
        context['page_num'] = page
        return context


class CoursesPageView(TemplateView):
    template_name = 'mainap/courses_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = [
            {
                'course_picture': 'img/course001.jpg',
                'course_name': 'Web Python',
                'course_number': 1
            }, {
                'course_picture': 'img/course002.jpg',
                'course_name': 'Web Golang',
                'course_number': 2
            }, {
                'course_picture': 'img/course003.jpg',
                'course_name': 'Web JavaScript',
                'course_number': 3
            }, {
                'course_picture': 'img/course004.jpg',
                'course_name': 'Web Java',
                'course_number': 4
            }, {
                'course_picture': 'img/course005.jpg',
                'course_name': 'Web PHP',
                'course_number': 5
            }, {
                'course_picture': 'img/course006.jpg',
                'course_name': 'Python AI',
                'course_number': 6
            }, {
                'course_picture': 'img/course007.jpg',
                'course_name': 'DevOps',
                'course_number': 7
            }
        ]
        return context


class ContactsPageView(TemplateView):
    template_name = 'mainap/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = [
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHcrhA',
                'city': 'Санкт‑Петербург',
                'phone': '+7-999-11-11111',
                'email': 'geeklab@spb.ru',
                'address': 'территория Петропавловская крепость, 3'
            },
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHX3xB',
                'city': 'Казань',
                'phone': '+7-999-22-22222',
                'email': 'geeklab@kz.ru',
                'address': 'территория Кремль, 11, Казань, Республика Татарстан, Россия'
            },
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHh9kD',
                'city': 'Москва',
                'phone': '+7-999-33-33333',
                'email': 'geeklab@msk.ru',
                'address': 'Красная площадь, 7, Москва, Россия'
            }
        ]
        return context


class DocSitePageView(TemplateView):
    template_name = 'mainap/doc_site.html'


class LoginPageView(TemplateView):
    template_name = 'mainap/login.html'

djangoBasics/BraniacLMC/mainap/templates/mainap/base.html
<!doctype html>
<html lang="ru">
{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">

    <link rel="icon"href="{% static 'favicon.ico' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

    <title>Контакты</title>
</head>

<body>


<!--МЕНЮ-->
{% include 'mainap/includes/main_menu.html' %}


<!--ЦЕНТРАЛЬНЫЙ БЛОК СТРАНИЦЫ-->
<div class="container-md">
    {% block content%}
    {% endblock content%}
</div>


<!--ФУТЕР-->
{% include 'mainap/includes/footer.html' %}

</body>

</html>

djangoBasics/BraniacLMC/mainap/templates/mainap/contacts.html
{% extends 'mainap/base.html' %}
{% load email_to_link %}
{% block content %}
<p>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Наши контакты</h1>
    <p class="lead">Обязательно свяжитесь с нами! Ваш комфорт - наша забота.</p>
  </div>
</div>
</p>
<p>
<div class="row justify-content-around mt-n2">
{% for sight in object_list %}
  <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
    <div class="card h-100 shadow">
      <div class="card-body">
        <div style="position:relative;overflow:hidden;">
          <iframe src="{{ sight.map }}" width="100%" height="300" frameborder="0" allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>
        </div>
        <h5 class="card-title">{{ sight.city }}</h5>
        <p class="card-text">
        <ul class="list-unstyled">
          <li>Телефон</li> <li><strong>{{ sight.phone }}</strong></li>
        </ul>
        <ul class="list-unstyled">
          <li>Email</li> <li><strong>{{ sight.email|email_to_link }} </strong></li>
        </ul>
        <ul class="list-unstyled">
          <li>Адрес</li> <li><strong>{{ sight.address }}</strong></li>
        </ul>
        </p>
      </div>
    </div>
  </div>
{% endfor %}
  
</div>
</p>



    </div>

{% endblock content %}

djangoBasics/BraniacLMC/mainap/templates/mainap/courses_list.html
{% extends 'mainap/base.html' %}
{% load static %}

{% block content %}

<div class="row justify-content-center mt-3">

    {% for course in object_list %}
            <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
            <a name='{{course.course_number}'> </a>
            <a href="#{{course.course_number}}">
                <img src="{% static course.course_picture %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title text-center">{{course.course_name}}</h5>
                </div>
            </a>
            </div>
    {% endfor course %}
</div>

<div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      {% for course_number in object_list %}
      <li class="page-item"><a class="page-link" href="#{{ course_number.course_number }}">{{ course_number.course_number }}</a></li>
      {% endfor %}
      <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
  </nav>
</div>

{% endblock content %}

djangoBasics/BraniacLMC/mainap/templates/mainap/doc_site.html
{% extends 'mainap/base.html' %}

{% block content %}
        
<div class="row justify-content-center align-items-center mt-3">
  <div class="col-md-9">
    <div class="card">
      <div class="card-header">
        Документация по сайту
      </div>
      <div class="card-body">

        <h5 class="card-title">CSS-стили</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://getbootstrap.com/docs/4.6/getting-started/introduction/" target="_blank">Bootstrap
              v4.6</a></li>
          <li><a href="https://bootswatch.com/lumen/" target="_blank">Bootstrap theme: Lumen</a></li>
        </ul>
        </p>

        <h5 class="card-title">Иконки</h5>
        <p class="card-text">
          <a href="https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use">FontAwesome 5.15.3</a>
        </p>

        <h5 class="card-title">Графики</h5>
        <p class="card-text">
          <a href="https://www.chartjs.org/">ChartJS</a>
        </p>

        <h5 class="card-title">Графика</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://www5.flamingtext.com/" target="_blank" rel="noopener noreferrer">Логотип by
              flamingtext.com</a></li>
          <li><a href="https://www.pexels.com/ru-ru" target="_blank" rel="noopener noreferrer">Фотографии by
              pexels.com</a>. Все изображения распространяются под бесплатной лицензией. Для страницы обзоров фотографии
            должны быть с соотношением сторон кратным 2.912 (например, 1920x659)</li>
          <li><a href="https://getavataaars.com/" target="_blank" rel="noopener noreferrer">Аватарки пользователей by
              getavataaars.com</a></li>
        </ul>
        </p>

      </div>
    </div>
  </div>
</div>


    </div>

{% endblock content %}

djangoBasics/BraniacLMC/mainap/templates/mainap/index.html
{% extends 'mainap/base.html' %}
{%load static %}

{% block content %}

    <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" style="background-color: #777; font-size: 1.25rem;">
            <div class="carousel-item active">
                <img src="{% static 'img/slider001.jpg' %}" class="d-block w-100" alt="" style="opacity: 0.3;">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Будь продуктивным</h3>
                    <p>Изучай только актуальные тренды современного IT</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/slider002.jpg' %}" class="d-block w-100" alt="" style="opacity: 0.3;">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Учись где угодно</h3>
                    <p>Парк, библиотека или дома под тёплым пледом - выбирай время и место учёбы сам</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/slider003.jpg' %}" class="d-block w-100" alt="" style="opacity: 0.3;">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Braniac - это МЫ</h3>
                    <p>Вливайся в нашу IT-тусовку - нас уже более 5000 брайниаков</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="jumbotron">
        <h1 class="display-4">Приветствую, путник!</h1>
        <p class="lead">
            На данном портале мы собрали сообщество людей объединённых одной целью - получать знания! В современном мире
            уже сложно представить человека не общающегося с компьютером. Повсеместное проникновение интернета дало
            возможность объеденить людей и сделать знания доступными как никогда ранее. У тебя есть уникальная
            возможность получить актуальные знания используя современные технологии. Не упусти свой шанс и переходи на
            вкладку "Курсы", записывайся на курсы и становись востребованным специалистом.
        </p>
    </div>

    <h3>Отзывы участников сообщества</h3>


    <div class="row text-center">

        
            <div class="col-lg-4">
                <img src="{% static 'img/user001.png' %}" alt="" style="max-width: 140px;">
                <h2>Лера</h2>
                <p>Выучила Python и получаю 300кк в секунду! Спасибо Браниаку!</p>
            </div>
        
            <div class="col-lg-4">
                <img src="{% static 'img/user002.png' %}" alt="" style="max-width: 140px;">
                <h2>Антоша</h2>
                <p>Больше не туплю в excel - только БД только хардкор!</p>
            </div>
        
            <div class="col-lg-4">
                <img src="{% static 'img/user003.png' %}" alt="" style="max-width: 140px;">
                <h2>Леонард</h2>
                <p>Как пропатчить KDE под FreeBSD?!</p>
            </div>
        

    </div>

    <div class="my-5">
        <hr>
    </div>

    <div class="row justify-content-center align-items-center">
        <div class="col-md-7">
            <h1>Сотни готовых курсов от лучших авторов</h1>
            <p>Выбирай из огромной коллекции готовых решений для самообразования</p>
        </div>
        <div class="col-md-5">
            <img src="{% static 'img/promo001.jpg' %}" alt="" class="w-100 h-100 rounded" style="opacity: 0.7;">
        </div>
    </div>

    <div class="my-5">
        <hr>
    </div>

    <div class="row justify-content-center align-items-center">
        <div class="col-md-5">
            <img src="{% static 'img/promo002.jpg' %}" alt="" class="w-100 h-100 rounded" style="opacity: 0.7;">
        </div>
        <div class="col-md-7">
            <h1>Монетизируй знания</h1>
            <p>Эксперт в свой области - давай к нам! Выгодные условия для тебя и пользователи со всего мира на нашей
                платформы</p>
        </div>
    </div>

    <div class="my-5">
        <hr>
    </div>

    <div class="row justify-content-center align-items-center">
        <div class="col-md-7">
            <h1>Вместе мы сила</h1>
            <p>Проекты любой сложности становятся легче, если ты в компании единомышленников. Присоединяйся!</p>
        </div>
        <div class="col-md-5">
            <img src="{% static 'img/promo003.jpg' %}" alt="" class="w-100 h-100 rounded" style="opacity: 0.7;">
        </div>
    </div>


    </div>

{% endblock content %}

djangoBasics/BraniacLMC/mainap/templates/mainap/login.html
<!doctype html>
<html lang="ru">
{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

    <title>Welcome to GeekLab!</title>
</head>

<body>





<div class="row justify-content-around align-items-center" style="height: 100vh; margin: 0px">
  <div class="text-center">
    <p>
      <a href="/"><img src="{% static 'img/logo.png' %}" alt=""></a>
    </p>
    <h2>Вход пользователя</h2>
    <form>
      <p>
        <input id="id_username" class="form-control" type="text" name="username" placeholder="Имя пользователя"
          required="" autofocus="">
      </p>
      <p>
        <input id="id_password" class="form-control" type="password" name="password" placeholder="Пароль" required="">
      </p>
      <p>
        <button type="submit" class="btn btn-primary btn-block">Войти</button>
      </p>
    </form>
    <p class="text-right">
      <a href=""><small>Забыли пароль?</small></a>
    </p>
    <h4>Вход через социальные сети</h4>
    <p>
    <div class="btn-group btn-block" role="group">
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-vk"></i></a>
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-github"></i></a>
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-facebook"></i></a>
    </div>
    </p>
  </div>
</div>



    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- ChartJs -->
    <script src="{% static 'js/Chart.min.js' %}"></script>

    <!-- FontAwesome -->
    <script src="{% static 'js/fontawesome.all.min.js' %}"></script>



</body>

</html>

djangoBasics/BraniacLMC/mainap/templates/mainap/news.html
{% extends 'mainap/base.html' %}

{% block content %}

<div class="row">

  <div class="col-lg-8">
    {% for news_item in json_news %}
    <div class="card my-2">
      <div class="card-body">
        <a name='{{ news_item.news_number }}'></a>
        <h5 class="card-title">{{ news_item.news_title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ news_item.news_date }}</h6>
        <p class="card-text">{{ news_item.news_text }}</p>
        <a href="#{{ news_item.news_number }}" class="card-link">Подробнее</a>
      </div>
    </div>
    {% endfor %}
    <div class="card my-2">
      <div class="card-body">
        <a name='7'></a>
        <h5 class="card-title">Новость со ссылкой</h5>
        <h6 class="card-subtitle mb-2 text-muted">Дата не установлена</h6>
        <p class="card-text">Какой-то текст со
        <a href="https://yandex.ru/search/?lr=116256&text=курс+доллара&src=suggest_B"
           class="card-link" target='_blank'>ссылкой</a>
        </p>
        <a href="#7" class="card-link">Подробнее</a>
      </div>
    </div>
    <div class="card my-2">
      <div class="card-body">
        <a name='8'></a>
        <h5 class="card-title">Новость со ссылкой и Get параметром</h5>
        <h6 class="card-subtitle mb-2 text-muted">Дата не установлена</h6>
        <p class="card-text">Какой-то текст со
        <a href="#1"
           class="card-link">ссылкой</a>
        </p>
        <a href="#8" class="card-link">Подробнее</a>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card my-2 sticky-top">
      <div class="card-header">
        Фильтры
      </div>
      <div class="card-body">
        <form action="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата от...</span>
            </div>
            <input type="date" class="form-control" name="dateFrom">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon2">Дата до...</span>
            </div>
            <input type="date" class="form-control" name="dateTo">
          </div>

          <button type="submit" class="btn btn-primary btn-block">Фильтровать</button>
        </form>
      </div>
    </div>
  </div>

</div>

<div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="{% url 'mainap:news_paginator' 1 %}?param1=foobar">Previous</a></li>
      {% for news_item in json_news %}
      <li class="page-item"><a class="page-link" href="#{{ news_item.news_number }}">{{ news_item.news_number }}</a></li>
      {% endfor %}
      <li class="page-item"><a class="page-link" href="{% url 'mainap:news_paginator' 10 %}">Next</a></li>
    </ul>
  </nav>
</div>


{% endblock content %}